[package]
name = "prokadiff-offtarget"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Reference-based CRISPR off-target search and oracle alignment framework"
readme.workspace = true

[dependencies]
prokadiff-gd = { workspace = true }
thiserror = { workspace = true }
