[package]
name = "prokadiff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "ProkaDiff CLI"
readme.workspace = true

[[bin]]
name = "prokadiff"
path = "src/main.rs"

[dependencies]
prokadiff-gd = { workspace = true }
prokadiff-evidence = { workspace = true }
prokadiff-classify = { workspace = true }
prokadiff-report = { workspace = true }
clap = { workspace = true }
